# Generated by Django 4.2.1 on 2023-05-09 16:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quickstart', '0002_friends'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendrequest',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='friendrequest',
            name='to_id',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='from_id',
        ),
        migrations.RemoveField(
            model_name='friends',
            name='to_id',
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='from_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequest',
            name='to_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='from_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friends',
            name='to_id',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
